apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus
  labels:
    app: prometheus
    tier: prometheus
  namespace: frankenstein
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: prometheus
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
          - name: config-job
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
          - name: prometheus-volume
            mountPath: /etc/prometheus
      volumes:
        - name: config-job
          configMap:
            name: prometheus-config
        - hostPath:
            path: /prometheus
          name: prometheus-volume