apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: frankenstein
spec:
  selector:
    app: grafana
  ports:
  - name: grafana-http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort