apiVersion: v1
kind: Service
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: db
  namespace: frankenstein
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql-server
  selector:
    name: mysql-server
  # type: NodePort